"""PDF export for solved Sudoku puzzles."""

from __future__ import annotations
from datetime import datetime
from io import BytesIO
from typing import Optional

import numpy as np

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image as RLImage,
    PageBreak,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT


# ============================================================
# Theme colors
# ============================================================

COLOR_PRIMARY   = colors.HexColor("#4f46e5")
COLOR_TEXT      = colors.HexColor("#0f172a")
COLOR_MUTED     = colors.HexColor("#64748b")
COLOR_BORDER    = colors.HexColor("#cbd5e1")
COLOR_BORDER_STRONG = colors.HexColor("#1e293b")
COLOR_GIVEN_BG  = colors.HexColor("#f8fafc")
COLOR_SOLVED_BG = colors.HexColor("#fef2f2")
COLOR_SOLVED_TX = colors.HexColor("#dc2626")
COLOR_EMPTY_TX  = colors.HexColor("#cbd5e1")


# ============================================================
# Board rendering
# ============================================================

def _board_table(board, given_mask=None, cell_size=14, color_mode="mixed"):
    """
    Render a 9×9 board as a ReportLab Table.

    Args:
        board:       np.ndarray (9, 9)
        given_mask:  boolean array — True for given cells
        cell_size:   cell size in mm
        color_mode:  "mixed" — original in black, solved in red
                     "plain" — everything black
    """
    if given_mask is None:
        given_mask = board > 0

    # Build the data grid
    data = []
    for r in range(9):
        row = []
        for c in range(9):
            v = int(board[r, c])
            row.append(str(v) if v != 0 else "")
        data.append(row)

    # Convert to strings and style
    table = Table(
        data,
        colWidths=[cell_size * mm] * 9,
        rowHeights=[cell_size * mm] * 9,
    )

    # Build style commands
    style_cmds = [
        ("ALIGN",     (0, 0), (-1, -1), "CENTER"),
        ("VALIGN",    (0, 0), (-1, -1), "MIDDLE"),
        ("FONTNAME",  (0, 0), (-1, -1), "Helvetica-Bold"),
        ("FONTSIZE",  (0, 0), (-1, -1), 11),
        ("TEXTCOLOR", (0, 0), (-1, -1), COLOR_TEXT),
        # outer border
        ("BOX",       (0, 0), (-1, -1), 1.2, COLOR_BORDER_STRONG),
    ]

    # Internal grid lines
    for i in range(1, 9):
        w = 1.2 if i % 3 == 0 else 0.4
        col = COLOR_BORDER_STRONG if i % 3 == 0 else COLOR_BORDER
        style_cmds.append(("LINEBEFORE", (i, 0), (i, -1), w, col))
        style_cmds.append(("LINEABOVE",  (0, i), (-1, i), w, col))

    # Color cells (only in mixed mode)
    if color_mode == "mixed":
        for r in range(9):
            for c in range(9):
                if board[r, c] == 0:
                    continue
                if given_mask[r, c]:
                    style_cmds.append(
                        ("BACKGROUND", (c, r), (c, r), COLOR_GIVEN_BG),
                    )
                else:
                    style_cmds.append(
                        ("BACKGROUND", (c, r), (c, r), COLOR_SOLVED_BG),
                    )
                    style_cmds.append(
                        ("TEXTCOLOR", (c, r), (c, r), COLOR_SOLVED_TX),
                    )

    table.setStyle(TableStyle(style_cmds))
    return table


# ============================================================
# Single-page export
# ============================================================

def _add_page_header(story, styles, title_text):
    """Common header used on every page."""
    h1 = ParagraphStyle(
        "H1",
        parent=styles["Heading1"],
        fontSize=22,
        textColor=COLOR_PRIMARY,
        spaceAfter=4,
        alignment=TA_LEFT,
        fontName="Helvetica-Bold",
    )
    sub = ParagraphStyle(
        "Sub",
        parent=styles["Normal"],
        fontSize=10,
        textColor=COLOR_MUTED,
        spaceAfter=14,
        alignment=TA_LEFT,
    )
    story.append(Paragraph(title_text, h1))
    story.append(Paragraph("Generated by Sudoku ML", sub))


def _add_info_block(story, record, styles):
    """Metadata block: date, difficulty, solver, time."""
    label_style = ParagraphStyle(
        "Lbl",
        parent=styles["Normal"],
        fontSize=9,
        textColor=COLOR_MUTED,
        fontName="Helvetica",
    )
    value_style = ParagraphStyle(
        "Val",
        parent=styles["Normal"],
        fontSize=11,
        textColor=COLOR_TEXT,
        fontName="Helvetica-Bold",
    )

    diff = record.get("difficulty", {}) or {}
    diff_label = diff.get("label", "—")
    diff_emoji = diff.get("emoji", "🟢")

    solver_label = "DLX (Dancing Links)" if record.get("solver_used") == "dlx" \
                   else "Backtracking"
    ts = record.get("timestamp", datetime.now())
    ts_str = ts.strftime("%Y-%m-%d %H:%M")

    rows = [
        [
            Paragraph("Date",        label_style),
            Paragraph("Difficulty",  label_style),
            Paragraph("Solver",      label_style),
            Paragraph("Time",        label_style),
        ],
        [
            Paragraph(ts_str,                        value_style),
            Paragraph(f"{diff_emoji} {diff_label}",  value_style),
            Paragraph(solver_label,                  value_style),
            Paragraph(f"{record.get('solver_time_ms', 0):.2f} ms", value_style),
        ],
    ]

    t = Table(rows, colWidths=[42 * mm, 42 * mm, 56 * mm, 34 * mm])
    t.setStyle(TableStyle([
        ("VALIGN",     (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 2),
        ("TOPPADDING",    (0, 1), (-1, 1), 2),
        ("LINEBELOW",  (0, 0), (-1, -1), 0.3, COLOR_BORDER),
    ]))
    story.append(t)
    story.append(Spacer(1, 6 * mm))


def _add_board_pair(story, record, styles):
    """Two boards side by side: original + solved."""
    board   = record.get("board")
    solution = record.get("solution")

    if board is None or solution is None:
        return

    given_mask = board > 0

    # Section labels
    sec_style = ParagraphStyle(
        "Sec",
        parent=styles["Normal"],
        fontSize=10,
        textColor=COLOR_MUTED,
        alignment=TA_CENTER,
        spaceAfter=3,
        fontName="Helvetica-Bold",
    )

    original_tbl = _board_table(board, given_mask, cell_size=11, color_mode="mixed")
    solved_tbl   = _board_table(solution, given_mask, cell_size=11, color_mode="mixed")

    left_col = Table(
        [[Paragraph("INPUT PUZZLE", sec_style)],
         [original_tbl]],
        colWidths=[100 * mm],
    )
    left_col.setStyle(TableStyle([
        ("ALIGN",  (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))

    right_col = Table(
        [[Paragraph("SOLUTION", sec_style)],
         [solved_tbl]],
        colWidths=[100 * mm],
    )
    right_col.setStyle(TableStyle([
        ("ALIGN",  (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))

    pair = Table(
        [[left_col, right_col]],
        colWidths=[105 * mm, 105 * mm],
    )
    pair.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ALIGN",  (0, 0), (-1, -1), "CENTER"),
    ]))
    story.append(pair)


def _add_stats_block(story, record, styles):
    """Small stats summary."""
    board = record.get("board")
    if board is None:
        return

    given_count = int(np.sum(board > 0))
    solved_count = 81 - given_count

    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=10,
        textColor=COLOR_TEXT,
        leading=15,
    )
    head_style = ParagraphStyle(
        "Head",
        parent=styles["Normal"],
        fontSize=11,
        textColor=COLOR_TEXT,
        fontName="Helvetica-Bold",
        spaceAfter=4,
    )

    story.append(Spacer(1, 8 * mm))
    story.append(Paragraph("Summary", head_style))
    story.append(Paragraph(
        f"<b>{given_count}</b> given digits · "
        f"<b>{solved_count}</b> cells solved by the algorithm",
        body_style,
    ))


def _add_thumbnail(story, record, styles):
    """Small original image thumbnail."""
    thumb_bytes = record.get("thumbnail_png")
    if not thumb_bytes:
        return

    try:
        img = RLImage(BytesIO(thumb_bytes), width=50 * mm, height=50 * mm)
    except Exception:
        return

    story.append(Spacer(1, 6 * mm))
    head_style = ParagraphStyle(
        "Head",
        parent=styles["Normal"],
        fontSize=11,
        textColor=COLOR_TEXT,
        fontName="Helvetica-Bold",
        spaceAfter=4,
    )
    story.append(Paragraph("Source Image", head_style))
    story.append(img)


def _add_footer(story, styles):
    """Closing line at the bottom."""
    footer = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        fontSize=8,
        textColor=COLOR_MUTED,
        alignment=TA_CENTER,
        spaceBefore=20,
    )
    story.append(Paragraph(
        "Generated by Sudoku ML · "
        "github.com/satanic-kangaroo/sudoku-ml",
        footer,
    ))


# ============================================================
# Public API
# ============================================================

def build_solution_pdf(record_dict: dict) -> bytes:
    """
    Build a single-page PDF for one solved puzzle.

    Args:
        record_dict: dict with keys:
            board, solution, difficulty, solver_used,
            solver_time_ms, timestamp, thumbnail_png

    Returns:
        PDF file as bytes.
    """
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title="Sudoku Solution",
        author="Sudoku ML",
    )

    styles = getSampleStyleSheet()
    story = []

    _add_page_header(story, styles, "Sudoku Solution")
    _add_info_block(story, record_dict, styles)
    _add_board_pair(story, record_dict, styles)
    _add_stats_block(story, record_dict, styles)
    _add_thumbnail(story, record_dict, styles)
    _add_footer(story, styles)

    doc.build(story)
    return buf.getvalue()


def build_history_pdf(records: list[dict]) -> bytes:
    """
    Build a multi-page PDF containing multiple solved puzzles.

    Args:
        records: list of record dicts (same shape as build_solution_pdf)

    Returns:
        PDF file as bytes.
    """
    if not records:
        raise ValueError("No records to export.")

    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title="Sudoku ML — History",
        author="Sudoku ML",
    )

    styles = getSampleStyleSheet()
    story = []

    # --- Cover page ---
    _add_page_header(story, styles, "Sudoku ML — History")

    cover_style = ParagraphStyle(
        "Cover",
        parent=styles["Normal"],
        fontSize=12,
        textColor=COLOR_TEXT,
        leading=20,
    )
    story.append(Paragraph(
        f"<b>{len(records)}</b> solved puzzle(s) in this report.",
        cover_style,
    ))
    story.append(Paragraph(
        f"Generated on {datetime.now().strftime('%Y-%m-%d at %H:%M')}",
        cover_style,
    ))
    story.append(Spacer(1, 10 * mm))

    # Quick summary table
    summary_rows = [["#", "Difficulty", "Solver", "Time"]]
    for i, rec in enumerate(records, 1):
        diff = rec.get("difficulty", {}) or {}
        label = f"{diff.get('emoji', '')} {diff.get('label', '—')}".strip()
        solver = "DLX" if rec.get("solver_used") == "dlx" else "BT"
        ms = f"{rec.get('solver_time_ms', 0):.1f} ms"
        summary_rows.append([str(i), label, solver, ms])

    summary_tbl = Table(summary_rows, colWidths=[20 * mm, 60 * mm, 40 * mm, 40 * mm])
    summary_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), COLOR_PRIMARY),
        ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
        ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",   (0, 0), (-1, -1), 10),
        ("ALIGN",      (0, 0), (-1, -1), "LEFT"),
        ("VALIGN",     (0, 0), (-1, -1), "MIDDLE"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING",    (0, 0), (-1, -1), 4),
        ("LINEBELOW",  (0, 0), (-1, 0), 0.6, COLOR_BORDER),
        ("LINEBELOW",  (0, 1), (-1, -2), 0.3, COLOR_BORDER),
    ]))
    story.append(summary_tbl)

    # --- Per-puzzle pages ---
    for i, rec in enumerate(records, 1):
        story.append(PageBreak())
        _add_page_header(story, styles, f"Puzzle #{i}")
        _add_info_block(story, rec, styles)
        _add_board_pair(story, rec, styles)
        _add_stats_block(story, rec, styles)

    _add_footer(story, styles)
    doc.build(story)
    return buf.getvalue()